export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_NEXT_PAGE_SUCCESS = 'ALL_PRODUCTS_NEXT_PAGE_SUCCESS'
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const PRODUCT_PAGE_INDEX = 'PRODUCT_PAGE_INDEX'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE'

export const UPDATE_SESSION_STORAGE_CART = 'UPDATE_SESSION_STORAGE_CART'
export const LOAD_SESSION_STORAGE_CART = 'LOAD_SESSION_STORAGE_CART'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_QUANTITY_TO_CART = 'ADD_QUANTITY_TO_CART'
export const REMOVE_QUANTITY_FROM_CART = 'REMOVE_QUANTITY_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
export const DESTROY_TOKEN = 'DESTROY_TOKEN'
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN'
export const GET_USER_INFO = 'GET_USER_INFO'
export const DESTROY_USER_INFO = 'DESTROY_USER_INFO'
export const ALL_CLIENTS = 'ALL_CLIENTS'
export const ALL_CLIENTS_SUCCESS = 'ALL_CLIENTS_SUCCESS'
export const ALL_CLIENTS_NEXT_PAGE_SUCCESS = 'ALL_CLIENTS_NEXT_PAGE_SUCCESS'
export const ALL_CLIENTS_FAILURE = 'ALL_CLIENTS_FAILURE'
